#include <memory>
#include <vector>
#include <algorithm>
#include <assert.h>
#include <random>
#include <map>
#include <string>
#include <unordered_set>
#include <map>
#include <cassert>
#include <sstream> 
#include <unordered_map>
#include <fstream>
#include <functional>
#include <algorithm>
#include <stdio.h>